version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=note-app
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./.db:/var/lib/mysql
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./docs/swagger.yml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
